def isPrime(x):
    for i in range(2, x - 1):
        if x % i == 0:
            return False
    return True

class FilterManager():
    def __init__(self, array):
        self.array = array
    def filt(self):
        return list(filter(lambda x : isPrime(x), self.array))


checking = FilterManager([1, 4, 6, 7, 14, 15, 16, 18, 19, 21, 28, 33, 36, 40, 49, 51, 54, 55, 56, 57, 59, 61, 62, 68, 69]) # array generated by random.org
print(checking.filt())